version: '2'
services:
  solr:
    image: solr:7.3.0
    volumes:
      - ./cores:/opt/solr/server/solr/cores
  app:
    build: .
    env_file:
      - .env
    command: bundle exec puma -w 2 -p 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - solr
      - redis_cache
    depends_on:
      - solr
  sidekiq_1:
      build: .
      command: bundle exec sidekiq  -c 1 -r /app
      volumes:
        - .:/app
      links:
        - redis
      env_file:
        - .env
  sidekiq_2:
    build: .
    command: bundle exec sidekiq  -c 1 -r /app
    volumes:
      - .:/app
    links:
      - redis
    env_file:
      - .env
  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
    ports:
      - '3035:3035'
  redis:
    image: redis:4.0.10
  redis_cache:
    image: redis:4.0.10
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
        - ./docker/redis-cache.conf:/usr/local/etc/redis/redis.conf