version: '3.1'

services:
  solr:
    image: umedia_solr:dev
    volumes:
      - ./snapshots:/snapshots
    # Uncomment to gain direct access to solr. Note: ensure your
    # firewall has been correctly configured and this port is not
    # exposed to the scary internet
    # ports: ["8983:8983"]

  solr_test:
    image: umedia_solr:test
    volumes:
      - ./snapshots_test:/snapshots
      - ./test_index:/test_index/

  app:
    build: .
    command: >
      bash -c "
        # Run test server detached
        RAILS_ENV=test SOLR_URL=http://solr_test:8983/solr/core UMEDIA_COLLECTION_PAGE_LIMIT=1 puma -b tcp://0.0.0.0:3001 -d &&

        # Run web server
        UMEDIA_COLLECTION_PAGE_LIMIT=20 puma -C config/puma.rb"
    ports: ['3000:3000', '3001:3001']
    env_file:
      - .env
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    links:
      - solr
      - redis_cache
    depends_on:
      - solr
      - solr_test

  sidekiq:
    build: .
    command: bundle exec sidekiq -q critical,2 -q default -c 1 -r /app
    volumes:
      - .:/app
    links:
      - redis
    env_file:
      - .env

  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
    ports: ['3035:3035']

  redis:
    image: redis:4.0.10

  redis_cache:
    image: redis:4.0.10
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
        - ./docker/redis-cache.conf:/usr/local/etc/redis/redis.conf

  selenium:
    image: selenium/standalone-chrome-debug:3.141.59-europium
    ports: ['4444:4444', '5900:5900']
    stdin_open: true
    tty: true