version: '2'
services:
  solr:
    image: umedia_solr:0.1.0
    volumes:
      - ./snapshots:/snapshots
  app:
    build: .
    env_file:
      - .env
    command: bundle exec puma -w 2 -p 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - solr
      - redis_cache
    depends_on:
      - solr
  sidekiq_1:
      build: .
      command: bundle exec sidekiq -q critical,2 -q default -c 5 -r /app
      volumes:
        - .:/app
      links:
        - redis
      env_file:
        - .env
  sidekiq_2:
      build: .
      command: bundle exec sidekiq -q critical,2 -q default -c 5 -r /app
      volumes:
        - .:/app
      links:
        - redis
      env_file:
        - .env
  sidekiq_3:
      build: .
      command: bundle exec sidekiq -q critical,2 -q default -c 5 -r /app
      volumes:
        - .:/app
      links:
        - redis
      env_file:
        - .env
  sidekiq_4:
      build: .
      command: bundle exec sidekiq -q critical,2 -q default -c 5 -r /app
      volumes:
        - .:/app
      links:
        - redis
      env_file:
        - .env

  redis:
    image: redis:4.0.10
  redis_cache:
    image: redis:4.0.10
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
        - ./docker/redis-cache.conf:/usr/local/etc/redis/redis.conf