version: '2'
services:
  solr:
    image: solr:7.3.0
    ports:
      - "8983:8983"
    volumes:
      - ./cores:/opt/solr/server/solr/cores
  web:
    build: .
    env_file:
      - .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - solr
      - redis
    depends_on:
      - solr
    environment:
      - GEONAMES_USER
      - GEONAMES_TOKEN
      - UMEDIA_NAILER_CDN_URI
      - UMEDIA_NAILER_API_URI
      - UMEDIA_NAILER_API_KEY
      - UMEDIA_NAILER_THUMB_FALLBACK_URL
  sidekiq:
      build: .
      command: bundle exec sidekiq  -c 10 -r /app
      volumes:
        - .:/app
      links:
        - redis
      env_file:
        - .env
      environment:
        - GEONAMES_USER
        - GEONAMES_TOKEN
  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    volumes:
      - .:/app
    ports:
      - '3035:3035'
  redis:
    image: redis:latest
  redis:
    image: redis:latest